import React from 'react';
import { AlertTriangle, CheckCircle, ShieldCheck, Scale } from 'lucide-react';
import { useSettingsStore } from '../../store/useSettingsStore';

export const RiskDisclaimerModal: React.FC = () => {
  const { riskDisclaimerAcknowledged, setRiskDisclaimerAcknowledged } = useSettingsStore();

  if (riskDisclaimerAcknowledged) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-xl p-4 animate-in fade-in duration-200">
      <div className="max-w-xl w-full glass-panel border border-amber-500/40 rounded-3xl p-6 sm:p-8 shadow-2xl space-y-6 relative overflow-hidden">
        {/* Ambient Top Glow */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="flex items-start gap-3.5 text-amber-400">
          <div className="p-3 bg-amber-500/15 border border-amber-500/30 rounded-2xl shrink-0">
            <AlertTriangle className="w-7 h-7 text-amber-400" />
          </div>
          <div>
            <span className="text-[10px] font-mono uppercase tracking-widest text-amber-400/90 font-bold block">
              REGULATORY &amp; RISK NOTICE
            </span>
            <h2 className="text-xl sm:text-2xl font-black text-white">Statistical Methodology Disclaimer</h2>
          </div>
        </div>

        <div className="space-y-3.5 text-xs text-slate-300 leading-relaxed bg-slate-950/70 border border-slate-800/90 rounded-2xl p-5 max-h-72 overflow-y-auto">
          <p className="font-semibold text-slate-100">
            Welcome to <span className="text-cyan-400">Deriv Digit Analyzer</span>. Please review the following core principles before proceeding:
          </p>
          <ul className="space-y-2 text-slate-300 list-disc list-inside text-xs">
            <li>
              <strong className="text-slate-100">Certified Random Number Generator (RNG):</strong> Deriv synthetic indices are generated by an independently audited and certified cryptographic RNG.
            </li>
            <li>
              <strong className="text-slate-100">Statistical Independence:</strong> Past digit draws have zero predictive correlation with future tick outcomes. Each draw is completely independent.
            </li>
            <li>
              <strong className="text-slate-100">Descriptive Variance Only:</strong> Signals, deviation scores, and streak metrics strictly describe historical variance from the 10.0% expected baseline. They are <strong>not predictions, guarantees, or edges</strong>.
            </li>
            <li>
              <strong className="text-slate-100">High-Risk Derivatives:</strong> Trading Digit Match, Differs, Over, and Under contracts involves substantial risk and can result in the loss of all staked funds.
            </li>
          </ul>
        </div>

        <div className="pt-2">
          <button
            onClick={() => setRiskDisclaimerAcknowledged(true)}
            className="w-full py-4 px-6 bg-gradient-to-r from-emerald-600 via-teal-600 to-emerald-600 hover:from-emerald-500 hover:to-teal-500 text-white font-extrabold text-sm rounded-2xl flex items-center justify-center gap-2.5 shadow-xl shadow-emerald-950/60 transition transform active:scale-95 cursor-pointer"
          >
            <CheckCircle className="w-5 h-5" />
            <span>I Acknowledge &amp; Accept the Terms</span>
          </button>
        </div>
      </div>
    </div>
  );
};
